name: testAction

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check
        run: |
          pwd
          ls -al
      - name: deploy
        uses: sand4rt/ftp-deployer@v1.7
        with:
          host: 211.106.171.118
          port: 22 # optional, default is: 21
          username: root # FTP username
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          remote_folder: /test # optional, remote path of your FTP server
          local_folder: ./ # optional, local path, default is: dist

          
          
           
        

           
        
