name: testAction

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: joutvhu/ftp-transfer@v1.0.0
        with:
          host: 211.106.171.118
          port: 22
          username: root
          password: ${{ secrets.FTP_PASSWORD }}
          commands: |
            pwd
            ls -al
            put . /test
        

           
        
