name: testAction

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: 211.106.171.118
          ftp-username: root
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /test
        
